import styles from "./Projects.module.css"
import image1 from "../../images/uzairkhansquare.jpeg"
import image5 from '../../images/Capture.JPG'
import image7 from '../../images/Capture111.JPG'
import image from "../../images/Capture25.JPG"
import hangmanLink from "../../images/hangman3.JPG"
import { useNavigate } from "react-router-dom"
export default function Projects(){
const navigate = useNavigate()
return(
    <>
       <section id="project-section" className={styles.section}>
        <div className={styles.headerSection}>
        <div className={styles.container}>

            <h3 className={styles.mainHeading}> 
            Projects
            </h3>
        <p className={styles.mainPara}>Take a look at what I've created.</p>

        </div>
        </div>
        <div className={styles.projectSection}>
        <h3 className={styles.secondaryHeading}>Basic Projects</h3>
<div className={styles.container}>        
                <div className={styles.basicProjects}>
                        <div className={styles.basicProject}>
                        <div className={styles.basicImageContainer}>
                                <img className={styles.basicImage} src={hangmanLink} alt="" srcset="" />
                        </div>
                                <h3 className={styles.basicTitle}>Hangman Game</h3>
                                <p className={styles.basicDescription}>A hangman game where you have to guess the word generated by computer by guessing the letters.</p>
                                <div className={styles.basicButtons}>
                               <a target="_blank" href="https://uzairsaleemkhan.github.io/Hangman-Application/">

                                <button  className={styles.basicWebsite}>See in Action</button>
                               </a>
                               <a target="_blank" href="https://github.com/Uzairsaleemkhan/Hangman-Application">
                                <button className={styles.basicCode}>GitHub Repo</button>
                               </a>
                                </div>
                        </div>
                        <div className={styles.basicProject}>
                        <div className={styles.basicImageContainer}>

                                <img className={styles.basicImage} src={image7} alt="" srcset="" />
                        </div>
                                <h3 className={styles.basicTitle}>Music Application</h3>
                                <p className={styles.basicDescription}>Listen to your favorite music on the go. And enjoy our playlist of some of the top songs.</p>
                                <div className={styles.basicButtons}>
                                <a href="https://uzairsaleemkhan.github.io/Music-Player-2/" target="_blank">

                                <button className={styles.basicWebsite}>See in Action</button>
                                </a>
                                <a href="https://github.com/Uzairsaleemkhan/Music-Player-2" target="_blank">

                                <button className={styles.basicCode}>GitHub Repo</button>
                                </a>
                                </div>
                        </div>
                        <div className={styles.basicProject}>
                        <div className={styles.basicImageContainer}>

                                <img className={styles.basicImage} src={image5} alt="" srcset="" />
                        </div>
                                <h3 className={styles.basicTitle}>Interactive Quiz App</h3>
                                <p className={styles.basicDescription}>Dive into the world of trivia with my Simple Quiz App, created with vanilla JavaScript!</p>
                                <div className={styles.basicButtons}>
                                <a target="_blank" href="https://quizapp-by-uzair-khan.onrender.com/">

                                <button className={styles.basicWebsite}>See in Action</button>
                                </a>
                                        <a href="https://github.com/Uzairsaleemkhan/Quiz-app" target="_blank">
                                <button className={styles.basicCode}>GitHub Repo</button>
                                        </a>                               
                                </div>
                        </div>
                       
                        </div>



            <h2 className={styles.secondaryHeading}>Capstone Project</h2>
            <div className={styles.project}>
                <div className={styles.left}>
                    <img className={styles.image} src={image} alt="" />
                </div>
                <div className={styles.right}>
                    {/* <h4 className={styles.secondaryHeading}>A Blog Platform</h4> */}
                    <p className={styles.description}>
                    A blog platform where users can create, edit, and delete blog posts with ease . 
                    </p>
                    <div className={styles.buttonContainer}>

                    <a href="https://uzairblogcrudapp.onrender.com/">
                    <button className={styles.website}> visit website</button>

                    </a>
                    <a href="https://github.com/Uzairsaleemkhan/personal-blog-frontend">
                    <button className={styles.code}> visit code</button>
                    </a>
                    </div>
                </div>
            </div>






            </div>
             

        </div>
       </section>
    </>
)

}